### ISSUE TITLE
Trackpad Occasionally Stops Working After Sleep

### ISSUE THREAD

**Issue by panda2k** [profzei/Matebook-X-Pro-2018#46] opened 2020-08-25 01:22 UTC
Once I close the lid to sleep my MBXP (2018), there is a chance that once I reawaken it, the trackpad stops working. This isn't a reproducible issue but it is annoying since it requires a full restart. I have already tried to update VoodooI2CHID.kext and VoodooI2C.kext to v2.4.4 but that hasn't fixed the issue. It might be of use to note that if I plug in an external mouse, I am able to control my cursor. I am on Catalina 10.15.6

**Comment by yamanadamnor** [comment] 2020-08-25 09:52
I am having the same issue. Also on catalina 10.15.6 and release 1.4.0 from this repo

**Comment by panda2k** [comment] 2020-08-25 22:37
I just found the fix. I changed the `wakedelay` to 1000 in `/efi/boot/oc/Kexts/VoodooPS2Controller.kext/Contents/Info.plist`. I then changed the `wakedelay` in `/efi/boot/oc/Kexts/VoodooPS2Controller.kext/Contents/VoodooPS2Trackpad.kext/Contents/Info.plist` to 10.

**Comment by panda2k** [comment] 2020-08-26 01:53
Update: this didn't fix it. After around an hour or more of sleep, trackpad stops working on wake up

**Comment by huotarih** [comment] 2020-08-27 09:00
I have the same issue. I already upgraded to big sur, still same issue. Lmk if you find a fix.

**Comment by R-Teer** [comment] 2020-08-27 14:51
Been having this issue since 10.15.5.  Restart seems to be the only fix

**Comment by hudp16** [comment] 2020-08-29 22:37
Have no trackpad whatsoever (but kb is fine) not sure what I'd want more.

**Comment by bfrorum10** [comment] 2020-08-31 12:06
Hello friends,

ich have the same Problem. Trackpad is not working after Sleep. did have any one the solution for this problem?

**Comment by jmalfara** [comment] 2020-09-02 23:57
I don't recall having this issue before 1.4.0 but no i get it. I might revert back to 1.3.0 and test

**Comment by profzei** [comment] 2020-09-03 06:06
...try to replace your config.plist with the following:
[config.plist.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5166508/config.plist.zip)
and, please, let me know your feedback (...our touchpad is quite weird in its behaviour) !

**Comment by elliotnash** [comment] 2020-09-03 20:43
The new config.plist doesn't seem to help, I'm still getting track pad freezes maybe every other sleep.

**Comment by pablott** [comment] 2020-09-04 20:59
> ...try to replace your `config.plist` with the following:
> [config.plist.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5166508/config.plist.zip)
> and, please, let me know your feedback (...our touchpad is quite weird in its behaviour) !

What's the difference in this plist? Other than the itlwm.kext setting.

**Comment by pablott** [comment] 2020-09-06 12:19
I can test suggestions and proide logs if that's needed.

**Comment by yamanadamnor** [comment] 2020-09-08 14:31
Any new updates on the trackpad issue?

**Comment by R-Teer** [comment] 2020-09-08 14:37
> ...try to replace your `config.plist` with the following:
> [config.plist.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5166508/config.plist.zip)
> and, please, let me know your feedback (...our touchpad is quite weird in its behaviour) !
> 
> Edit: btw `itlwm.kext` is enabled in the above mentioned config.plist (only because I use it): please check your kexts before using `config.plist` (if you don't want use it, please, put accordingly `false` attribute)

Currently testing this plist @profzei, all seems pretty good so far, had a single isolated issue where i had no trackpad after waking from sleep - touchscreen continued to function though which is much better, allowed me to save any open documents at least.  Will let you know if I find any further issues!

**Comment by profzei** [comment] 2020-09-08 20:27
@R-Teer Thank you very much for your feedback! ...nobody else?

**Comment by profzei** [comment] 2020-09-08 22:02
> What's the difference in this plist? Other than the itlwm.kext setting.

@pablott : I re-enabled `VoodooPS2Mouse` and `VoodooPS2Trackpad.kext`... they were previously disabled in Release 1.1.0 in July according to acidanthera buglist

> I can test suggestions and provide logs if that's needed.

@pablott : thank you very much...
Is your feedback still negative?
... this issue (for me) only appeared after applying Supplemental Update on 10.15.6, not before

**Comment by R-Teer** [comment] 2020-09-09 11:06
> @R-Teer Thank you very much for your feedback! ...nobody else?

Hey @profzei, hope you are well man!

I have been able to recreate the issue quite a few times now, having spend the past hour repeating the following;

1. Connect to AC power
2. Close lid of device
3. Wait around 5 minutes
4. Disconnect AC adapter
5. Wait 5 minutes
6. Open lid and wake from sleep

I have been able to recreate the issue about 5 or 6 times successfully.

This is occurring with both the old and new plist.  I have also tried updating VoodooI2C and I2CHID to the latest versions from rehabman, and still facing the same issues. I'm currently running OS 11 and latest Opencore.

I hope this helps my friend!

R

**Comment by profzei** [comment] 2020-09-09 12:32
@R-Teer Hi, I can't use my MBXP till tomorrow afternoon... so I can only suggest some more tests:

1- does the issue appear if sleep&wake phases are both on AC or on battery? I can guess the answer is no... at least in my case...

2- try to disable in config.plist 2 things: SSDT-ADP1.aml and the patch AC0_ to ADP1 (the need to be disabled together...)

It seems to me that the issue may be related to AC plug on&off during sleep&wake phases (I never do that before in my daily use)... 

Please, at the moment, do not update VoodooI2C and VoodooI2CHID to 2.4.4+ since we are using a modified 2.4.3 version to fix some random boot issue for our "very annoying" touchpad!😆

**Comment by yamanadamnor** [comment] 2020-09-09 13:23
the new config.plist did not fix anything in my case. Im running 10.15.6 on release 1.4.0 with itlwm kext enabled.

**Comment by profzei** [comment] 2020-09-10 11:11
@yamanadamnor Have you also tried what I suggested yesterday in my previous post?

**Comment by yamanadamnor** [comment] 2020-09-11 06:23
> @yamanadamnor Have you also tried what I suggested yesterday in my previous post?

I will try and report back

**Comment by yamanadamnor** [comment] 2020-09-12 12:48
> @yamanadamnor Have you also tried what I suggested yesterday in my previous post?
Unfortunately your suggestions did not fix the issue. The trackpad is still broken after sleep.  Although i noticed that the trackpad worked for a split second upon opening the lid.

**Comment by profzei** [comment] 2020-09-13 15:43
Hi everybody this issue seems to be **general** i.e. related to `VoodooI2C & company`. For reference see
- [issue #371](https://github.com/VoodooI2C/VoodooI2C/issues/371)
- [issue #325](https://github.com/VoodooI2C/VoodooI2C/issues/325)
- [issue #319](https://github.com/VoodooI2C/VoodooI2C/issues/319)
- [issue #318](https://github.com/VoodooI2C/VoodooI2C/issues/318)

**Work in progress** to fix it!

**Comment by pablott** [comment] 2020-09-14 21:12
> > What's the difference in this plist? Other than the itlwm.kext setting.
> 
> @pablott : I re-enabled `VoodooPS2Mouse` and `VoodooPS2Trackpad.kext`... they were previously disabled in Release 1.1.0 in July according to acidanthera buglist
> 
> > I can test suggestions and provide logs if that's needed.
> 
> @pablott : thank you very much...
> Is your feedback still negative?
> ... this issue (for me) only appeared after applying Supplemental Update on 10.15.6, not before...
> 
> I'll make a new release in a few days surely before weekend!

I couldn't test yet. I'm on 10.15.6 and always been I think, so I can't really compare. I don't think this was caused by plugging/unplugging to AC. I keep my laptop in a drawer and occassionally take it out, without plugging to AC. It still happens, usually after hours of sleeping.
It seems is a bug in the Voodoo kext based on your last post so I may wait for a new release with the fix.

**Comment by wiregen** [comment] 2020-09-17 01:04
I have a ThinkPad T460S running opencore. The git I was using migrated from VoodooI2C to VoodooRMI and it was so much better. Could something like that be implemented on the MateBook X Pro?

**Comment by pablott** [comment] 2020-09-20 20:36
> I have a ThinkPad T460S running opencore. The git I was using migrated from VoodooI2C to VoodooRMI and it was so much better. Could something like that be implemented on the MateBook X Pro?

Can you share the git repo? Maybe we can learn something form the plist that they are using.

**Comment by wiregen** [comment] 2020-09-21 00:51
> > I have a ThinkPad T460S running opencore. The git I was using migrated from VoodooI2C to VoodooRMI and it was so much better. Could something like that be implemented on the MateBook X Pro?
> 
> Can you share the git repo? Maybe we can learn something form the plist that they are using.

Here you go! https://github.com/VoodooSMBus/VoodooRMI

**Comment by wiregen** [comment] 2020-09-23 02:49
> > I have a ThinkPad T460S running opencore. The git I was using migrated from VoodooI2C to VoodooRMI and it was so much better. Could something like that be implemented on the MateBook X Pro?
> 
> Can you share the git repo? Maybe we can learn something form the plist that they are using.

Sorry here is the repo for the T460S Im using that uses VoodooRMI - https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore

**Comment by profzei** [comment] 2020-09-23 08:05
@wiregen : I'm trying to use VoodooRMI & VoodooSMBus project, but, at the moment, both touchpad and touchscreen are not working at all! I'll open an issue on the project section... maybe it's only a "not-yet supported device" issue!

**Comment by wiregen** [comment] 2020-09-25 21:21
Interesting observation today. I updated my matebook x pro to 10.15.7 and I have woken my laptop about 5 times and the trackpad works each time. Beforehand the first or second time the trackpad would stop working. Will continue to test.

**Comment by profzei** [comment] 2020-09-25 21:28
@wiregen I updated too my MBXP to 10.15.7, but I'm trying to use `RMII2C` (i.e. `VoodooI2C` + `VoodooRMI` since the couple `VoodooSMBus` + `VoodooRMI` seems not working) as suggested... Now I'll revert back to `VoodooI2C` + `VoodooI2CHID` and continue testing... Thanks!

**Comment by profzei** [comment] 2020-09-29 22:18
@wiregen **and anyone interested...**
could you, please, test the behaviour of the following updated `SSDT-TPXX.aml`?
[SSDT-TPXX.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5302112/SSDT-TPXX.aml.zip)

I'm using macOS Catalina **10.15.7**: if you update your machine, please, keep in mind to apply first fixes suggested in **Power management: Hibernation** section
Bios version 1.28

Please, let me know your feedback

**Comment by wiregen** [comment] 2020-09-29 23:41
> @wiregen **and anyone interested...**
> could you, please, test the behaviour of the following updated `SSDT-TPXX.aml`?
> [SSDT-TPXX.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5302112/SSDT-TPXX.aml.zip)
> 
> I'm using macOS Catalina **10.15.7**: if you update your machine, please, keep in mind to apply first fixes suggested in **Power management: Hibernation** section
> Bios version 1.28
> 
> Please, let me know your feedback

Trying it now! Will report back after testing!

**Comment by profzei** [comment] 2020-09-30 09:40
@wiregen **and anyone interested to help...**
Please use the `SSDT-TPXX.aml` file present in the above post **with** the following file:
[SSDT-ADP1.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5304544/SSDT-ADP1.aml.zip)

...thank you for your help!

**Comment by yamanadamnor** [comment] 2020-10-01 11:07
> @wiregen **and anyone interested to help...**
> Please use the `SSDT-TPXX.aml` file present in the above post **with** the following file:
> [SSDT-ADP1.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5304544/SSDT-ADP1.aml.zip)
> 
> ...thank you for your help!

Is it possible to revert back to macOS catalina after upgrading to Big Sur without resetting all my data?

**Comment by profzei** [comment] 2020-10-01 13:12
> Is it possible to revert back to macOS catalina after upgrading to Big Sur without resetting all my data?

I'm not an expert... but I guess you don't get a such chance... since upgrading to BS your experience could only improve... at least this is macOS perspective!

**Comment by wiregen** [comment] 2020-10-01 15:24
> @wiregen **and anyone interested to help...**
> Please use the `SSDT-TPXX.aml` file present in the above post **with** the following file:
> [SSDT-ADP1.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5304544/SSDT-ADP1.aml.zip)
> 
> ...thank you for your help!

Trying out the new SSDT-ADP1.aml I found that my trackpad would freeze 2/3 times coming out of sleep. Previously, my trackpad i would say would freeze 1/4 times. Reverting to my previous SSDT to do more thorough testing.

**Comment by profzei** [comment] 2020-10-01 17:33
@wiregen I agree with you: the combination new `SSDT-TPXX.aml` & new `SSDT-ADP1.aml` is not the right choice...

Try, as you said, new `SSDT-TPXX.aml` and old `SSDT-ADP1.aml`

Then, please, try also this "new new" `SSDT-TPXX.aml`
[SSDT-TPXX.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5313753/SSDT-TPXX.aml.zip)

For the latter case, please, if you could, report your feedback for:
- new new `SSDT-TPXX.aml` + new `SSDT-ADP1.aml`
- new new `SSDT-TPXX.aml` + old `SSDT-ADP1.aml `

I'm not a fool asking so many trials... 
What's the difference between the old `SSDT-ADP1.aml` and new one? In the old one, we use the `_PRW` (_Power Resource for Wake_) planned by our machine MBXP while in the new one, instead, we use the `_PRW` made for MacBookPro...

What's the difference between new `SSDT-TPXX.aml` and _new new_ `SSDT-TPXX.aml`? In both cases, I'm applying hints from @zhen-zen as suggested in [VoodooRMI #67](https://github.com/VoodooSMBus/VoodooRMI/issues/67), but the problem is that we do not have a `SHUB` device attached to our `TPD0` or `TPL1` (it is not present in our `DSDT.aml`) so we need to try one by one...

Any help is very appreciated!

Btw, it seems that our bug i.e. "trackpad occasionally stops working after wake-up" also affected `VoodooRMI`

**Comment by wiregen** [comment] 2020-10-01 19:05
> @wiregen I agree with you: the combination new `SSDT-TPXX.aml` & new `SSDT-ADP1.aml` is not the right choice...
> 
> Try, as you said, new `SSDT-TPXX.aml` and old `SSDT-ADP1.aml`
> 
> Then, please, try also this "new new" `SSDT-TPXX.aml`
> [SSDT-TPXX.aml.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5313753/SSDT-TPXX.aml.zip)
> 
> For the latter case, please, if you could, report your feedback for:
> 
> * new new `SSDT-TPXX.aml` + new `SSDT-ADP1.aml`
> * new new `SSDT-TPXX.aml` + old `SSDT-ADP1.aml `
> 
> I'm not a fool asking so many trials...
> What's the difference between the old `SSDT-ADP1.aml` and new one? In the old one, we use the `_PRW` (_Power Resource for Wake_) planned by our machine MBXP while in the new one, instead, we use the `_PRW` made for MacBookPro...
> 
> What's the difference between new `SSDT-TPXX.aml` and _new new_ `SSDT-TPXX.aml`? In both cases, I'm applying hints from @zhen-zen as suggested in [VoodooRMI #67](https://github.com/VoodooSMBus/VoodooRMI/issues/67), but the problem is that we do not have a `SHUB` device attached to our `TPD0` or `TPL1` (it is not present in our `DSDT.aml`) so we need to try one by one...
> 
> Any help is very appreciated!
> 
> Btw, it seems that our bug i.e. "trackpad occasionally stops working after wake-up" also affected `VoodooRMI`

Will do, will report my findings.

**Comment by profzei** [comment] 2020-10-05 17:16
@wiregen : Hi, here are my thoughts:

Using the `VoodooI2C` modified version 2.4.3 present in this repo, the best combination for me is made by _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml` since I can report, during my daily use, _zero_ issues after 37 sleep&wake-up phases...
Could you confirm this "result"?

Yesterday, `VoodooI2C` released v. 2.4.5 (v.2.4.4 is bugged for our device...) implementing **only** two of the three fixes present in the modified 2.4.3 we are actually using... so now I'd like to test the behaviour of this new release with the combo _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml`

**Comment by yamanadamnor** [comment] 2020-10-05 18:07
> @wiregen : Hi, here are my thoughts:
> 
> Using the `VoodooI2C` modified version 2.4.3 present in this repo, the best combination for me is made by _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml` since I can report, during my daily use, _zero_ issues after 37 sleep&wake-up phases...
> Could you confirm this "result"?
> 
> Yesterday, `VoodooI2C` released v. 2.4.5 (v.2.4.4 is bugged for our device...) implementing **only** two of the three fixes present in the modified 2.4.3 we are actually using... so now I'd like to test the behaviour of this new release with the combo _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml`

I would like to help as much as I can. What do you need me to do? Thanks for the tremendous effort you have put in to make this laptop run so smoothly on macOS.

**Comment by panda2k** [comment] 2020-10-06 02:51
> @wiregen : Hi, here are my thoughts:
> 
> Using the `VoodooI2C` modified version 2.4.3 present in this repo, the best combination for me is made by _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml` since I can report, during my daily use, _zero_ issues after 37 sleep&wake-up phases...
> Could you confirm this "result"?
> 
> Yesterday, `VoodooI2C` released v. 2.4.5 (v.2.4.4 is bugged for our device...) implementing **only** two of the three fixes present in the modified 2.4.3 we are actually using... so now I'd like to test the behaviour of this new release with the combo _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml`

Thanks for creating this fix. I'll be testing this in the coming days.

**Comment by wiregen** [comment] 2020-10-06 13:58
> @wiregen : Hi, here are my thoughts:
> 
> Using the `VoodooI2C` modified version 2.4.3 present in this repo, the best combination for me is made by _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml` since I can report, during my daily use, _zero_ issues after 37 sleep&wake-up phases...
> Could you confirm this "result"?
> 
> Yesterday, `VoodooI2C` released v. 2.4.5 (v.2.4.4 is bugged for our device...) implementing **only** two of the three fixes present in the modified 2.4.3 we are actually using... so now I'd like to test the behaviour of this new release with the combo _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml`

Hey there - I tried the new new SSDT-TPXX.aml and the new SSDT-ADP1.aml and I was getting freezing. After reading your findings, I decided to start again from scratch from your repo's OC folder here and just copied my SMBIOS settings over and the SSDT-TPXX.aml and the SSDT-ADP1.aml you attached here. Crossing my fingers here!

I have a couple of questions:
1.  Is your OC folder in your repo the latest revisions you made? I saw the releases section is over 30 days old
2. Do I need to clear the nvram for EFI OC changes to take effect?

Some other changes - I deleted the itlwm.kext in your OC and followed your instructions to use the AirportItlwm.kext - so far it's working great!

**Comment by profzei** [comment] 2020-10-06 16:36
@wiregen 

> Is your OC folder in your repo the latest revisions you made? I saw the releases section is over 30 days old

Yes, in my repo you can find the latest revision (in general it is not always stable since sometimes I needed to revert back from some experiments...). Next release for Catalina should be in next weekend with OC v. 0.6.2 and more stuff for improving battery life.

> Do I need to clear the nvram for EFI OC changes to take effect?

No, you can use it only if you think there is something weird...

> I see in the changelog you added SSDT-FnKey.aml - I had to remap my modifer keys in system preferences -> keyboard to use alt as command and the windows key as option. Was this by design?

You only need to disable your remap... A user opened an issue asking for this feature that honestly I forgot to implement previously...

Happy for AirportItlwm!

**Comment by panda2k** [comment] 2020-10-09 00:32
> > @wiregen : Hi, here are my thoughts:
> > Using the `VoodooI2C` modified version 2.4.3 present in this repo, the best combination for me is made by _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml` since I can report, during my daily use, _zero_ issues after 37 sleep&wake-up phases...
> > Could you confirm this "result"?
> > Yesterday, `VoodooI2C` released v. 2.4.5 (v.2.4.4 is bugged for our device...) implementing **only** two of the three fixes present in the modified 2.4.3 we are actually using... so now I'd like to test the behaviour of this new release with the combo _new new_ `SSDT-TPXX.aml` + new `SSDT-ADP1.aml`
> 
> Hey there - I tried the new new SSDT-TPXX.aml and the new SSDT-ADP1.aml and I was getting freezing. After reading your findings, I decided to start again from scratch from your repo's OC folder here and just copied my SMBIOS settings over and the SSDT-TPXX.aml and the SSDT-ADP1.aml you attached here. Crossing my fingers here!
> 
> I have a couple of questions:
> 
> 1. Is your OC folder in your repo the latest revisions you made? I saw the releases section is over 30 days old
> 2. Do I need to clear the nvram for EFI OC changes to take effect?
> 3. I see in the changelog you added SSDT-FnKey.aml - I had to remap my modifer keys in system preferences -> keyboard to use alt as command and the windows key as option. Was this by design?
> 
> Some other changes - I deleted the itlwm.kext in your OC and followed your instructions to use the AirportItlwm.kext - so far it's working great!

I also tried the new new SSDT-TPXX.aml and the new SSDT-ADP1.aml and I still got trackpad freezing.

**Comment by wiregen** [comment] 2020-10-09 01:08
> @wiregen
> 
> > Is your OC folder in your repo the latest revisions you made? I saw the releases section is over 30 days old
> 
> Yes, in my repo you can find the latest revision (in general it is not always stable since sometimes I needed to revert back from some experiments...). Next release for Catalina should be in next weekend with OC v. 0.6.2 and more stuff for improving battery life.
> 
> > Do I need to clear the nvram for EFI OC changes to take effect?
> 
> No, you can use it only if you think there is something weird...
> 
> > I see in the changelog you added SSDT-FnKey.aml - I had to remap my modifer keys in system preferences -> keyboard to use alt as command and the windows key as option. Was this by design?
> 
> You only need to disable your remap... A user opened an issue asking for this feature that honestly I forgot to implement previously...
> 
> Happy for AirportItlwm!
> 
> **Update**
> 
> 1. I'm using `VoodooI2C` 2.5  as stated in previous post for testing it with _new new_ `SSDT-TPXX.aml` and `SSDT-ADP1.aml`: at the moment 7 sleep&wake-up cycles and no issue... crossing fingers here too!
> 2. If you follow their [Gitter page](http://gitter.im/alexandred/VoodooI2C) you can see that, at the moment, there is some mess with `VoodooI2C` release bumped first to 2.5, then 2.5.1 and then reverted back to 2.4.4... so we need to have patience for a completely debugged version...

Hey there Profzei, I am getting still getting trackpad freezes also using your new SSDTs. But they do seem pretty occasional. This is about my 6th lid opening today and it froze around that. I'll wait for your release, I'll just start fresh with your OC folder when you release your update.

**Comment by yamanadamnor** [comment] 2020-10-09 10:20
I have been testning with the _new new_ `SSDT-TPXX.aml` and _new_ `SSDT-ADP1.aml` for a few days and it did help alot. I was able to have around 4-6 sleep cycles before the trackpad stopped working. This is alot better than before but still not ideal. Im happy to test new configs and report back.


My EFI folder:
[EFI.zip](https://github.com/profzei/Matebook-X-Pro-2018/files/5354200/EFI.zip)

**Comment by profzei** [comment] 2020-10-12 13:26
Hi all, I just made release v. 1.6.0 using new VoodooI2C v. 2.5.2... It seems quite stable, but not perfect (still some bugs ahimé...): I ran into the same issue after 12 sleep & wake-up phases.
At this point I really don't know what I'm supposed to do for resolving this issue apart reverting back to VoodooI2C v. 2.3! (but in that case experience with gestures was less smooth!)

**Comment by zhen-zen** [comment] 2020-10-12 18:53
> Hi all, I just made release v. 1.6.0 using new VoodooI2C v. 2.5.2... It seems quite stable, but not perfect (still some bugs ahimé...): I ran into the same issue after 12 sleep & wake-up phases.
> At this point I really don't know what I'm supposed to do for resolving this issue apart reverting back to VoodooI2C v. 2.3! (but in that case experience with gestures was less smooth!)

Quite weird, maybe do a binary search like `git-bisect`? One issue I have run into during 2.3 -2.4 has "Timed out waiting for bus to change state" in log. However, I have no idea since there's nothing strange in your log.

**Comment by tlefko** [comment] 2020-10-26 13:55
any fix found yet? have same issue

**Comment by mcoolidge** [comment] 2020-10-28 00:40
Same here. It seems to freeze 4/5 times after sleep even on the latest versions.

**Comment by profzei** [comment] 2020-10-29 20:57
@mcoolidge @tlefko 
Hi, atm, there is not a significant update for this issue: it's related on VoodooI2C v. 2.5.2 as stated in many posts in various forums and for a lot of hackintosh configuration. It's not a specific issue for our configuration or our machine...

If you like, you could use VoodooI2C and VoodooI2CHID v. 2.3: it's the latest release which was working fine, i.e. no issue after wake-up... but with a worse feeling for gestures... but you can use it as a fall-back just until an official fix by VoodooI2C team

Atm I worked a lot for improving network experience... and I think I'm happy about it... I'll make a release within a few days

**Comment by mcoolidge** [comment] 2020-10-29 21:16
Thanks profzei! Let me know if I can help with anything.

**Comment by tlefko** [comment] 2020-10-29 21:17
> @mcoolidge @tlefko
> Hi, atm, there is not a significant update for this issue: it's related on VoodooI2C v. 2.5.2 as stated in many posts in various forums and for a lot of hackintosh configuration. It's not a specific issue for our configuration or our machine...
> 
> If you like, you could use VoodooI2C and VoodooI2CHID v. 2.3: it's the latest release which was working fine, i.e. no issue after wake-up... but with a worse feeling for gestures... but you can use it as a fall-back just until an official fix by VoodooI2C team
> 
> Atm I worked a lot for improving network experience... and I think I'm happy about it... I'll make a release within a few days

was going to say, I can't get Airportitlwm enabled in both Big Sur and Catalina, invalid kext parameter

**Comment by tlefko** [comment] 2020-10-29 21:19
> > @mcoolidge @tlefko
> > Hi, atm, there is not a significant update for this issue: it's related on VoodooI2C v. 2.5.2 as stated in many posts in various forums and for a lot of hackintosh configuration. It's not a specific issue for our configuration or our machine...
> > If you like, you could use VoodooI2C and VoodooI2CHID v. 2.3: it's the latest release which was working fine, i.e. no issue after wake-up... but with a worse feeling for gestures... but you can use it as a fall-back just until an official fix by VoodooI2C team
> > Atm I worked a lot for improving network experience... and I think I'm happy about it... I'll make a release within a few days
> 
> was going to say, I can't get Airportitlwm enabled in both Big Sur and Catalina, invalid kext parameter.
> 
> Currently am using clover with i2c 2.4 and have smooth gestures btw, and Airportitlwm -- want to switch to OC for Big Sur though

you can use the IO80211 family kext integrated with Airportitlwm as a plugin perhaps, that's how I enabled it on clover 

-all the best

**Comment by profzei** [comment] 2020-10-29 21:28
> was going to say, I can't get Airportitlwm enabled in both Big Sur and Catalina, invalid kext parameter.
> Currently am using clover with i2c 2.4 and have smooth gestures btw, and Airportitlwm -- want to switch to OC for Big Sur though
> 
> you can use the IO80211 family kext integrated with Airportitlwm as a plugin perhaps, that's how I enabled it on clover
> 
> -all the best

Atm I'm using `AirportItlwm.kext` without any issue on **OC 0.6.2** following what I wrote on **Network** section... I abandoned Clover some months ago... I can also say that I created a **compact version** for `AirportItlwm.kext` which is only 2-3 MB instead of 10 MB... this is one of the items I'm working on these days and it will be available in a few days as stated above...

**Comment by tlefko** [comment] 2020-10-29 21:42
> > was going to say, I can't get Airportitlwm enabled in both Big Sur and Catalina, invalid kext parameter.
> > Currently am using clover with i2c 2.4 and have smooth gestures btw, and Airportitlwm -- want to switch to OC for Big Sur though
> > you can use the IO80211 family kext integrated with Airportitlwm as a plugin perhaps, that's how I enabled it on clover
> > -all the best
> 
> Atm I'm using `AirportItlwm.kext` without any issue on **OC 0.6.2** following what I wrote on **Network** section... I abandoned Clover some months ago... I can also say that I created a **compact version** for `AirportItlwm.kext` which is only 2-3 MB instead of 10 MB... this is one of the items I'm working on these days and it will be available in a few days as stated above...

yeah, im not sure what I did wrong --- im not experienced with open core, I followed your instructions for the forcekexttoload option. regardless, I look forward to the release :)

**Comment by Vatri91** [comment] 2020-11-12 22:34
Was it possible to fix the bug in the last update from today?

**Comment by profzei** [comment] 2020-11-12 23:17
@Vatri91 
Hi, I'm still working on it... time for experimenting long sleep periods is not much since I'm using MBXP as my daily driver...
🤞🏻

**Comment by isuke01** [comment] 2020-11-17 15:38
@profzei 
Hey, I see this trackpad issue with almost every third sleep with BigSur 11.0.1, OC 0.6.3. even for not long sleeps like few minutes. If I can provide somehow logs for that I would be glad to help (I'm not sure how to get logs or something that can help to debug this issue)

**Comment by sagar-chandarana** [comment] 2020-11-21 11:59
I imagine this is very annoying for people. Thanks for all your work @profzei just bought you a coffee.

**Comment by sagar-chandarana** [comment] 2020-11-21 12:33
I replaced VoodooI2C.kext and VoodooI2CHID.kext with v2.3 and it just stopped booting, stuck at apple logo. What am I missing?

**Comment by profzei** [comment] 2020-11-21 18:06
@sagar-chandarana Thank you so much for your appreciation!
Are you using Big Sur 11.0.1 Public Release? ...and release 1.7.0?
Honestly, now I'm testing `hibernatemode 25` so hibernate instead of sleep while I am monitoring the evolution of the state of VoodooI2C

@isuke01 Are you using latest release 1.7.0? If I remember well, your post was in the morning while my release was in the evening... sorry but I was very busy...

**Comment by sagar-chandarana** [comment] 2020-11-23 02:33
@profzei I am still on Catalina latest update for now. Would be curious to know, for track pad, are things are more stable with Big Sur? Does Hibernate work natively? Perhaps too early to say atm. Will wait a bit before I upgrade my daily work machine

**Comment by isuke01** [comment] 2020-11-23 12:26
@profzei 
Hey, sorry I was busy too, we all have work and live  I can undestand it :)
No I wasn't on 1.7.0 as far as I remember I think it wasn't there yet, I'll do some testing today hopefully since I want to test some performance against Windows in some apps :)

**Comment by profzei** [comment] 2020-11-24 17:56
@sagar-chandarana 

> Does Hibernate work natively?

I'm testing it... 'till now all is fine but I'm not able to "first sleep & then hibernate" but only hibernate closing lid for now... wip

**Comment by sagar-chandarana** [comment] 2020-11-24 18:28
Got it. Good luck!

**Comment by LavenderMP** [comment] 2020-11-25 06:16
I solve this problem when using disable touch screen.
hope that help

**Comment by profzei** [comment] 2020-11-25 16:56
@LavenderMP Thank you for your feedback!
Also for me, **'till now**, **touchpad is working well after sleep&wake-up phase disabling touchscreen...** this seems to be supported by @fewtarius's opinions in `VoodooI2C` issue section where he stated that the `MultiGPIO` feature enabled in `VoodooI2C` kext is **buggy**... so since we have two I2C devices (i.e. touchpad & touchscreen) a conservative approach is disabling one of them... i.e. touchscreen until an official fix will be released by `VoodooI2C` team.

Please, anyone interested [see here](https://github.com/profzei/Matebook-X-Pro-2018/issues/92#issuecomment-731615905) using `SSDT-DTPD.aml` and related `config.plist`.
If your feedback will be positive, then I'll add them in next release...

**Comment by Vatri91** [comment] 2020-11-25 19:22
Nice to hear that :) We already have a hackintosh that works perfectly :)

**Comment by ldan93** [comment] 2020-11-26 19:05
Disabling the touchscreen also seems to fix the issue on my side : 3rd day without any trackpad failure. Wonderful :)

**Comment by wiregen** [comment] 2020-11-27 15:38
This is day 3 for me also with no trackpad freezing from wake! Woohoo!

**Comment by mcoolidge** [comment] 2020-11-28 22:29
It's been a few days for me with the .aml file and modified config. No issues so far!

**Comment by sagar-chandarana** [comment] 2020-11-28 23:53
upvoting this to be included as an official fix in the next release, along with a patch for people who would like to reenable touch

**Comment by panda2k** [comment] 2020-11-29 00:52
New .aml and modified config have completely fixed trackpad issues for me. I'm on 11.0.1 too.

**Comment by profzei** [comment] 2020-11-29 12:22
@panda2k @sagar-chandarana @mcoolidge @wiregen @ldan93 @Vatri91 @LavenderMP In Italian spoke we say: "Bene bene bene!" Thank you very much for your feedback! This fix will be included in the next maintenance release scheduled immediately after the next Acidanthera team update!

**Closed by profzei** 2020-11-29 12:22 UTC
